source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use Puma as the app server
gem 'puma', '~> 4.3'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making
# cross-origin AJAX possible
#
# To use this: "If you're working with Rails 5, un-comment out the
# rack-cors gem from your Gemfile and bundle install. Then, open up
# `config/initializers/cors.rb`, which was provided for you.
# Uncomment out the content of that file and specify your allowed origins."
#
# gem 'rack-cors'

# Use Foreman for starting both the Rails and React Webpack servers locally
gem 'foreman', '~> 0.82.0'

# Use Enumerize to provide a cleaner wrapper around typed enum/string data.
gem 'enumerize', '~> 2.0'

# Use ActiveModelSerializers to provide control over generating JSON from Models
gem 'active_model_serializers', '~> 0.10'

# Use bcrypt for encrypting user passwords to store in the database
# used for ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1'

# Use rubocop for linting Ruby code
gem 'rubocop', '~> 0.46'

group :development, :test do
  # Call 'byebug' in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri

  # Use RSpec as the rails test runner https://github.com/rspec/rspec-rails
  gem 'rspec-rails', '~> 3.5'
  # Use FactoryGirl to assist with quickly mocking objects for tests
  gem 'factory_girl_rails', '~> 4.8'
  # Use Faker to assist with mocking data for test objects
  gem 'faker', '~> 1.7'

  # Code coverage monitoring via https://coveralls.io/
  gem 'coveralls', '~> 0.8'
end

group :development do
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in
  # the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
